### ISSUE TITLE
Light scrollbars showing in dark theme.

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#182]
As discussed in #180. In a dark theme the markup webview shows light scroll bars in a dark theme. 
![screen shot 2016-03-22 at 18 38 18](https://cloud.githubusercontent.com/assets/1826271/13988464/faaa25ae-f103-11e5-8418-077350dff10e.png)

Rendering done by JavaFX and webview.

Could this link be useful for a possible fix?  

Although I can hide the scrollbars with:
body {
    overflow-y: hidden; 
}
However, this also disables scrolling (not just hides the bar).

I can't seem to change the colour as mentioned here
http://stackoverflow.com/questions/15418628/javafx-2-webview-how-to-enhance-the-scrollbars
 via:

::-webkit-scrollbar-track  {
    background-color: transparent;
}
    
::-webkit-scrollbar-thumb {
    background: transparent;
}

Also this may be useful:
http://stackoverflow.com/questions/2279978/webview-showing-white-bar-on-right-side

**Comment by vsch** [comment]
@yunti, great info. Here is what I found to work. You have to set the width otherwise the rest is ignored.

```css
/* width setting is required or nothing is changed */
::-webkit-scrollbar {
    width: 18px;
}
::-webkit-scrollbar-track  {
    background-color: black;
}
/* the slider or "thumb" has some rounded edges and a shadow and it's a little translucent */
::-webkit-scrollbar-thumb {
    border-radius: 6px;
    box-shadow: inset 0 0 6px rgba(0,0,0,0.5); 
    background: rgba(159,192,192,0.8);
}
::-webkit-scrollbar-thumb:vertical {
    min-height: 40px;
}
```

The top/bottom arrow boxes are missing but the color match is much easier on the eyes. If you improve on this please let me know.

I will include these settings in the darcula-fx.css file used for the Darcula WebView stylesheet in the next release.

**Comment by yunti** [comment]
@vsch, great fix, well done, for finding out what was blocking it. I changed it slightly to make it less obtrusive, but that's probably too invisible for most users, so I would keep yours as the default.

```
/* width setting is required or nothing is changed */
::-webkit-scrollbar {
    width: 6px;
}
::-webkit-scrollbar-track  {
    background-color: black;
}
/* the slider or "thumb" has some rounded edges and a shadow and it's a little translucent */
::-webkit-scrollbar-thumb {
    border-radius: 6px;
    box-shadow: inset 0 0 6px rgba(0,0,0,0.5); 
    background: rgba(68,68,68,0.8);
}
::-webkit-scrollbar-thumb:vertical {
    min-height: 40px;
```

**Comment by vsch** [comment]
@yunti, here is the updated version with up/down buttons and better color match to Darcula.

<img width="819" alt="screen shot 2016-03-23 at 6 28 33 pm" src="https://cloud.githubusercontent.com/assets/10299086/14002877/32f507b4-f125-11e5-8376-5ddd281171fc.png">

```css
/* scroll bar color change to match the dark scheme */
/* width setting is required or nothing is changed */
::-webkit-scrollbar {
  width: 18px;
   background: #2B2B2B;
}

::-webkit-scrollbar-button {
  width: 18px;
  height: 18px;
  background: #4B4B4B;
  border: 1px solid #4B4B4B;
  border-radius: 0px;
}

::-webkit-scrollbar-thumb {
  background: #666666;
  border: 1px solid #959595;
  border-radius: 2px;
}
::-webkit-scrollbar-thumb:hover {
  background: #929292;
}
::-webkit-scrollbar-thumb:active {
  background: #929292;
}
::-webkit-scrollbar-thumb:vertical {
    min-height: 40px;
}
::-webkit-scrollbar-track {
  background: #4B4B4B;
  border: 2px solid #4B4B4B;
  border-radius: 0px;
}
::-webkit-scrollbar-track:hover {
  background: #666666;
}
::-webkit-scrollbar-track:active {
  background: #333333;
}
::-webkit-scrollbar-corner {
  background: #999999;
}

::-webkit-scrollbar-button:vertical:start {
    width: 18px;
    height: 18px;
    background-repeat: no-repeat;
    background-position: center;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAICAYAAAAvOAWIAAAKpGlDQ1BJQ0MgUHJvZmlsZQAASImVlwdUE9kax+/MpBdaAAEpoffeQXoNXTqISkgoocSYEEBERURUYC2oiIANXaqCq1JkLYAotkXBgn2DLCrquliwofIGeIT33nl73nn/Offkd7755rvf3Ln3nH8AoFxm8njpsBQAGdxMfqiPOz06JpaOFwEIvYjopcRkCXhuISEB4G/18S6ai+qW8XStv8/7r5JmJwpYAEAhKCewBawMlE+h4ziLx88EAGGjcc3sTN40b0ZZlo82iHL1NCfP8vFpTpjl3pmc8FAPlO8BQKAwmfxkAMh/oHF6FisZrUPBoGzGZXO4KFuh7MxKYaLzUNB7wCgjY8U0H0RZL+Ff6iT/W80EcU0mM1nMs+8yI4InR8BLZ676P5fjfysjXTg3hwY6KCl839Dp+dA1q09b4S9mbkJQ8Bxz2LM9TXOK0DdijlkCj9g5ZjM9/edYmBbhNsdM/vyznExG+BzzV4SK6ycKvMLE9RMZAeIe0oPEnMTxZsxxbkp41BxncSKD5liQFuY/n+MhjvOFoeKek/je4nfMEMz3xmLO95CZEu4731u0uAd2oqeXOM6NEOfzMt3FNXnpIeL8xHQfcVyQFSZ+NhPdYHOcyvQLma8TIl4fwAGBgAlYmYk50/sKeKzgreJzklMy6W7oKUmkM7gsEyO6hZm5DQDTZ272k76/N3OWIHnCfExwGwAHHTTInY8tKwKg0xYA2p/zMa08dB8eBuDsIEvIz5qNTW91gAUkIAlkgSJQBZpADxgDC2ADHIEr8AJ+IBiEgxiwDLBACsgAfJAN8sB6UARKwHawG1SCA+AwqAfHwAnQDs6AbnAJXAM3wR3wEIjAKHgFxsFHMAlBEB6iQjRIEVKDtCFDyAKyg5whLygACoVioHgoGeJCQigP2gCVQGVQJXQIaoB+gU5D3dAVaAC6Dw1DY9A76CuMwBRYFlaBdWBT2A52g/3hcHgpnAyvhHPhQngrXAHXwEfhNrgbvgbfgUXwK3gCAQgZkUfUEWPEDvFAgpFYJAnhI2uRYqQcqUGakU6kD7mFiJDXyBcMDkPD0DHGGEeMLyYCw8KsxKzFlGIqMfWYNkwv5hZmGDOO+YGlYpWxhlgHLAMbjU3GZmOLsOXYWmwr9iL2DnYU+xGHw8njdHG2OF9cDC4VtxpXituHa8F14QZwI7gJPB6viDfEO+GD8Ux8Jr4Ivxd/FH8eP4gfxX8mkAlqBAuCNyGWwCUUEMoJjYRzhEHCc8IkUYqoTXQgBhPZxFXEbcQjxE7iDeIocZIkTdIlOZHCSamk9aQKUjPpIukR6T2ZTNYg25MXkznkfHIF+Tj5MnmY/IUiQzGgeFDiKELKVkodpYtyn/KeSqXqUF2psdRM6lZqA/UC9Qn1swRNwkSCIcGWWCdRJdEmMSjxRpIoqS3pJrlMMleyXPKk5A3J11JEKR0pDymm1FqpKqnTUkNSE9I0aXPpYOkM6VLpRukr0i9k8DI6Ml4ybJlCmcMyF2RGaAhNk+ZBY9E20I7QLtJGZXGyurIM2VTZEtljsv2y43IyclZykXI5clVyZ+VE8oi8jjxDPl1+m/wJ+bvyXxeoLHBbkLhgy4LmBYMLPiksVHBVSFQoVmhRuKPwVZGu6KWYprhDsV3xsRJGyUBpsVK20n6li0qvF8oudFzIWli88MTCB8qwsoFyqPJq5cPK15UnVFRVfFR4KntVLqi8VpVXdVVNVd2lek51TI2m5qzGUduldl7tJV2O7kZPp1fQe+nj6srqvupC9UPq/eqTGroaERoFGi0ajzVJmnaaSZq7NHs0x7XUtAK18rSatB5oE7XttFO092j3aX/S0dWJ0tmk067zQldBl6Gbq9uk+0iPqueit1KvRu+2Pk7fTj9Nf5/+TQPYwNogxaDK4IYhbGhjyDHcZzhghDWyN+Ia1RgNGVOM3YyzjJuMh03kTQJMCkzaTd6YapnGmu4w7TP9YWZtlm52xOyhuYy5n3mBeaf5OwsDC5ZFlcVtS6qlt+U6yw7Lt1aGVolW+63uWdOsA603WfdYf7exteHbNNuM2WrZxttW2w7ZydqF2JXaXbbH2rvbr7M/Y//FwcYh0+GEw1+Oxo5pjo2OLxbpLkpcdGTRiJOGE9PpkJPIme4c73zQWeSi7sJ0qXF56qrpynatdX3upu+W6nbU7Y27mTvfvdX9k4eDxxqPLk/E08ez2LPfS8YrwqvS64m3hneyd5P3uI+1z2qfLl+sr7/vDt8hhgqDxWhgjPvZ+q3x6/Wn+If5V/o/DTAI4Ad0BsKBfoE7Ax8FaQdxg9qDQTAjeGfw4xDdkJUhvy7GLQ5ZXLX4Wah5aF5oXxgtbHlYY9jHcPfwbeEPI/QihBE9kZKRcZENkZ+iPKPKokTRptFroq/FKMVwYjpi8bGRsbWxE0u8luxeMhpnHVcUd3ep7tKcpVeWKS1LX3Z2ueRy5vKT8dj4qPjG+G/MYGYNcyKBkVCdMM7yYO1hvWK7snexxxKdEssSnyc5JZUlvUh2St6ZPJbiklKe8prjwankvE31TT2Q+iktOK0ubSo9Kr0lg5ARn3GaK8NN4/auUF2Rs2KAZ8gr4olWOqzcvXKc78+vFUCCpYKOTFnU3FwX6gk3CoeznLOqsj5nR2afzJHO4eZcX2Wwasuq57neuT+vxqxmre7JU89bnze8xm3NobXQ2oS1Pes01xWuG833ya9fT1qftv63ArOCsoIPG6I2dBaqFOYXjmz02dhUJFHELxra5LjpwGbMZs7m/i2WW/Zu+VHMLr5aYlZSXvKtlFV69Sfznyp+mtqatLV/m822/dtx27nb7+5w2VFfJl2WWzayM3Bn2y76ruJdH3Yv332l3Kr8wB7SHuEeUUVARcderb3b936rTKm8U+Ve1VKtXL2l+tM+9r7B/a77mw+oHCg58PUg5+C9Qz6H2mp0asoP4w5nHX52JPJI3892PzfUKtWW1H6v49aJ6kPrextsGxoalRu3NcFNwqaxo3FHbx7zPNbRbNx8qEW+peQ4OC48/vKX+F/unvA/0XPS7mTzKe1T1a201uI2qG1V23h7SruoI6Zj4LTf6Z5Ox87WX01+rTujfqbqrNzZbedI5wrPTZ3PPT/Rxet63Z3cPdKzvOfhhegLt3sX9/Zf9L94+ZL3pQt9bn3nLztdPnPF4crpq3ZX26/ZXGu7bn299Tfr31r7bfrbbtje6Lhpf7NzYNHAuUGXwe5bnrcu3WbcvnYn6M7A3Yi794bihkT32Pde3E+///ZB1oPJh/mPsI+KH0s9Ln+i/KTmd/3fW0Q2orPDnsPXn4Y9fTjCGnn1h+CPb6OFz6jPyp+rPW94YfHizJj32M2XS16OvuK9mnxd9Kf0n9Vv9N6c+sv1r+vj0eOjb/lvp96Vvld8X/fB6kPPRMjEk48ZHyc/FX9W/Fz/xe5L39eor88ns7/hv1V81//e+cP/x6OpjKkpHpPPnLECCDrgpCQA3tUBQI1BvcNNAEgSs554RtCsj58h8Hc865tnhDqXui4Apq2Zfz4AB9FfnWlLio4QVwDCXQFsaSke/5QgydJitha5HbUm5VNT71EviNcH4PvQ1NRk+9TU91q02QcAdH2c9eLTwqH/UJqR7i+ejjeCtuaD/9A/AMP6AIl0f5ngAAAAjklEQVQYGWNgoAR0dHREgDA2MxiRBTs7O/2A/I1QMf/y8vJNyPJMMA7QtBiowsNA+giIDRWDKWEAm9zV1VX4////PkZGxrNlZWUmIFmg2BmgmDFQrOjbt2+zGxoavoBNBikEyh+DKQQphrKPgeS4uLjyQGJgxUDdUd+/f7cHCSADkBhI7s+fP2uQxYliAwD0Tzq2l7F8DAAAAABJRU5ErkJggg==)
}

::-webkit-scrollbar-button:vertical:end {
    width: 18px;
    height: 18px;
    background-repeat: no-repeat;
    background-position: center;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAICAYAAAAvOAWIAAAKpGlDQ1BJQ0MgUHJvZmlsZQAASImVlwdUE9kax+/MpBdaAAEpoffeQXoNXTqISkgoocSYEEBERURUYC2oiIANXaqCq1JkLYAotkXBgn2DLCrquliwofIGeIT33nl73nn/Offkd7755rvf3Ln3nH8AoFxm8njpsBQAGdxMfqiPOz06JpaOFwEIvYjopcRkCXhuISEB4G/18S6ai+qW8XStv8/7r5JmJwpYAEAhKCewBawMlE+h4ziLx88EAGGjcc3sTN40b0ZZlo82iHL1NCfP8vFpTpjl3pmc8FAPlO8BQKAwmfxkAMh/oHF6FisZrUPBoGzGZXO4KFuh7MxKYaLzUNB7wCgjY8U0H0RZL+Ff6iT/W80EcU0mM1nMs+8yI4InR8BLZ676P5fjfysjXTg3hwY6KCl839Dp+dA1q09b4S9mbkJQ8Bxz2LM9TXOK0DdijlkCj9g5ZjM9/edYmBbhNsdM/vyznExG+BzzV4SK6ycKvMLE9RMZAeIe0oPEnMTxZsxxbkp41BxncSKD5liQFuY/n+MhjvOFoeKek/je4nfMEMz3xmLO95CZEu4731u0uAd2oqeXOM6NEOfzMt3FNXnpIeL8xHQfcVyQFSZ+NhPdYHOcyvQLma8TIl4fwAGBgAlYmYk50/sKeKzgreJzklMy6W7oKUmkM7gsEyO6hZm5DQDTZ272k76/N3OWIHnCfExwGwAHHTTInY8tKwKg0xYA2p/zMa08dB8eBuDsIEvIz5qNTW91gAUkIAlkgSJQBZpADxgDC2ADHIEr8AJ+IBiEgxiwDLBACsgAfJAN8sB6UARKwHawG1SCA+AwqAfHwAnQDs6AbnAJXAM3wR3wEIjAKHgFxsFHMAlBEB6iQjRIEVKDtCFDyAKyg5whLygACoVioHgoGeJCQigP2gCVQGVQJXQIaoB+gU5D3dAVaAC6Dw1DY9A76CuMwBRYFlaBdWBT2A52g/3hcHgpnAyvhHPhQngrXAHXwEfhNrgbvgbfgUXwK3gCAQgZkUfUEWPEDvFAgpFYJAnhI2uRYqQcqUGakU6kD7mFiJDXyBcMDkPD0DHGGEeMLyYCw8KsxKzFlGIqMfWYNkwv5hZmGDOO+YGlYpWxhlgHLAMbjU3GZmOLsOXYWmwr9iL2DnYU+xGHw8njdHG2OF9cDC4VtxpXituHa8F14QZwI7gJPB6viDfEO+GD8Ux8Jr4Ivxd/FH8eP4gfxX8mkAlqBAuCNyGWwCUUEMoJjYRzhEHCc8IkUYqoTXQgBhPZxFXEbcQjxE7iDeIocZIkTdIlOZHCSamk9aQKUjPpIukR6T2ZTNYg25MXkznkfHIF+Tj5MnmY/IUiQzGgeFDiKELKVkodpYtyn/KeSqXqUF2psdRM6lZqA/UC9Qn1swRNwkSCIcGWWCdRJdEmMSjxRpIoqS3pJrlMMleyXPKk5A3J11JEKR0pDymm1FqpKqnTUkNSE9I0aXPpYOkM6VLpRukr0i9k8DI6Ml4ybJlCmcMyF2RGaAhNk+ZBY9E20I7QLtJGZXGyurIM2VTZEtljsv2y43IyclZykXI5clVyZ+VE8oi8jjxDPl1+m/wJ+bvyXxeoLHBbkLhgy4LmBYMLPiksVHBVSFQoVmhRuKPwVZGu6KWYprhDsV3xsRJGyUBpsVK20n6li0qvF8oudFzIWli88MTCB8qwsoFyqPJq5cPK15UnVFRVfFR4KntVLqi8VpVXdVVNVd2lek51TI2m5qzGUduldl7tJV2O7kZPp1fQe+nj6srqvupC9UPq/eqTGroaERoFGi0ajzVJmnaaSZq7NHs0x7XUtAK18rSatB5oE7XttFO092j3aX/S0dWJ0tmk067zQldBl6Gbq9uk+0iPqueit1KvRu+2Pk7fTj9Nf5/+TQPYwNogxaDK4IYhbGhjyDHcZzhghDWyN+Ia1RgNGVOM3YyzjJuMh03kTQJMCkzaTd6YapnGmu4w7TP9YWZtlm52xOyhuYy5n3mBeaf5OwsDC5ZFlcVtS6qlt+U6yw7Lt1aGVolW+63uWdOsA603WfdYf7exteHbNNuM2WrZxttW2w7ZydqF2JXaXbbH2rvbr7M/Y//FwcYh0+GEw1+Oxo5pjo2OLxbpLkpcdGTRiJOGE9PpkJPIme4c73zQWeSi7sJ0qXF56qrpynatdX3upu+W6nbU7Y27mTvfvdX9k4eDxxqPLk/E08ez2LPfS8YrwqvS64m3hneyd5P3uI+1z2qfLl+sr7/vDt8hhgqDxWhgjPvZ+q3x6/Wn+If5V/o/DTAI4Ad0BsKBfoE7Ax8FaQdxg9qDQTAjeGfw4xDdkJUhvy7GLQ5ZXLX4Wah5aF5oXxgtbHlYY9jHcPfwbeEPI/QihBE9kZKRcZENkZ+iPKPKokTRptFroq/FKMVwYjpi8bGRsbWxE0u8luxeMhpnHVcUd3ep7tKcpVeWKS1LX3Z2ueRy5vKT8dj4qPjG+G/MYGYNcyKBkVCdMM7yYO1hvWK7snexxxKdEssSnyc5JZUlvUh2St6ZPJbiklKe8prjwankvE31TT2Q+iktOK0ubSo9Kr0lg5ARn3GaK8NN4/auUF2Rs2KAZ8gr4olWOqzcvXKc78+vFUCCpYKOTFnU3FwX6gk3CoeznLOqsj5nR2afzJHO4eZcX2Wwasuq57neuT+vxqxmre7JU89bnze8xm3NobXQ2oS1Pes01xWuG833ya9fT1qftv63ArOCsoIPG6I2dBaqFOYXjmz02dhUJFHELxra5LjpwGbMZs7m/i2WW/Zu+VHMLr5aYlZSXvKtlFV69Sfznyp+mtqatLV/m822/dtx27nb7+5w2VFfJl2WWzayM3Bn2y76ruJdH3Yv332l3Kr8wB7SHuEeUUVARcderb3b936rTKm8U+Ve1VKtXL2l+tM+9r7B/a77mw+oHCg58PUg5+C9Qz6H2mp0asoP4w5nHX52JPJI3892PzfUKtWW1H6v49aJ6kPrextsGxoalRu3NcFNwqaxo3FHbx7zPNbRbNx8qEW+peQ4OC48/vKX+F/unvA/0XPS7mTzKe1T1a201uI2qG1V23h7SruoI6Zj4LTf6Z5Ox87WX01+rTujfqbqrNzZbedI5wrPTZ3PPT/Rxet63Z3cPdKzvOfhhegLt3sX9/Zf9L94+ZL3pQt9bn3nLztdPnPF4crpq3ZX26/ZXGu7bn299Tfr31r7bfrbbtje6Lhpf7NzYNHAuUGXwe5bnrcu3WbcvnYn6M7A3Yi794bihkT32Pde3E+///ZB1oPJh/mPsI+KH0s9Ln+i/KTmd/3fW0Q2orPDnsPXn4Y9fTjCGnn1h+CPb6OFz6jPyp+rPW94YfHizJj32M2XS16OvuK9mnxd9Kf0n9Vv9N6c+sv1r+vj0eOjb/lvp96Vvld8X/fB6kPPRMjEk48ZHyc/FX9W/Fz/xe5L39eor88ns7/hv1V81//e+cP/x6OpjKkpHpPPnLECCDrgpCQA3tUBQI1BvcNNAEgSs554RtCsj58h8Hc865tnhDqXui4Apq2Zfz4AB9FfnWlLio4QVwDCXQFsaSke/5QgydJitha5HbUm5VNT71EviNcH4PvQ1NRk+9TU91q02QcAdH2c9eLTwqH/UJqR7i+ejjeCtuaD/9A/AMP6AIl0f5ngAAAAmklEQVQYGWNgIAEwgtR2dXVFfvv2bXVDQ8MfZL1APgsXF1fonz9/zlZVVd1iAkn+//9/GScn50FkhSA2SAwkx8LCEgLigxUzMjIWAdlWQBvOgARBAMq2AskBbZ0EEgM7A8To6OiIAUosBjIPQ8VtgKbGVlRULAHJgwBcMYjT2dnpB6Q2gthA4F9eXr4JwsRBAm2IAGEc0sQLAwB01zTsJKQDAgAAAABJRU5ErkJggg==)
}
```
