### ISSUE TITLE
Incomplete Tasks in Task list not rendering correctly

### ISSUE THREAD

**Issue by jimkohl** [vsch/idea-multimarkdown#183]
GH Flavored Markdown ToDo / Task list feature not rendering tasks that haven't been completed correctly.  Using IJ 2016.1 on Mac.

The plugin is rendering completed items correctly, but incomplete items don't get an empty checkbox.
Here's the md:
## MUST
- [x] this is a complete item  
- [ ] this is an incomplete item  

Here's the rendering:
![screen shot 2016-03-23 at 10 43 11 am]
![image](https://cloud.githubusercontent.com/assets/5053517/13988826/21b3d002-f0e4-11e5-900b-227b83a5a644.png)

thanks
jim

**Comment by vsch** [comment]
@jimkohl, thanks for finding this one. It  only affects the Swing preview but can be addressed in the custom CSS until the next release.

Add the following to CSS custom text:

```css
ul li.taski,
ul li.taskp,
ul li.dtask,
ul li.dtaskp {
    list-style-type: square;
    padding-left: inherit;
    text-indent: inherit;
}
```

<img width="973" alt="screen shot 2016-03-23 at 12 20 34 pm" src="https://cloud.githubusercontent.com/assets/10299086/13992229/b41d72ba-f0f1-11e5-8404-0367a18baedf.png">
