### ISSUE TITLE
Code sections not exactly monospace in preview

### ISSUE THREAD

**Issue by Mc128k** [vsch/idea-multimarkdown#526]
Hi, I'm trying to draw diagrams in the markdown file, like this:

    ╔═══════════╗   ╔═══════════╗   ╔════════════╗
    ║  G Cloud  ║   ║  G Cloud  ║   ║  G Cloud   ║
    ║ FM Server ║◀──║  Web API  ║◀──║ Job Status ║
    ╚═══════════╝   ╚═══════════╝   ╚════════════╝
          ▲               ▲
          └───────┐       └────────┐
    ╔═══════════╗ │ ╔═══════════╗  │╔════════════╗
    ║  Dev Env  ║ │ ║  Dev Env  ║  │║  Dev Env   ║
    ║ FM Server ║◀┴─║  Web API  ║◀─┘║ Job Status ║
    ╚═══════════╝   ╚═══════════╝   ╚════════════╝

However, the app just scrambles the content when using the HTML preview:

<img width="339" alt="screen shot 2017-11-12 at 15 20 53" src="https://user-images.githubusercontent.com/3678359/32699886-1aa1f058-c7bd-11e7-8437-0ccb0e0f1b03.png">

This is due to the space as being handles with a different width, i.e. the font seems not exactly monospace.

Using version 2.3.8 with IntelliJ WebStorm

**Comment by vsch** [comment]
@Mc128k, it depends on the fonts installed on your system. Here is what it looks like on my system:

![image](https://user-images.githubusercontent.com/10299086/32705231-b8fb22f2-c7df-11e7-8fbb-a268f3998f78.png)

The CSS for fixed fonts has the following font list:

```css
var,
code,
kbd {
    font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
    font-size: 12px;
}

pre {
    margin-top: 0;
    margin-bottom: 0;
    font: 12px Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```

Previous reports of non-fixed font used where fixed pitch was expected was either caused by
incorrect font installation or by removing some of the font family names from above list.

You can add the above CSS snippet to Custom CSS Text under Languages & Frameworks > Markdown >
Stylesheet: 

![Screenshot_Stylesheet](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Stylesheet.png)
