### ISSUE TITLE
Couldn't we reflect font specification to preview?

### ISSUE THREAD

**Issue by hokkun-dayo** [vsch/idea-multimarkdown#531]
I've specified to custom CSS as follows:
```css
body {
  font-family: Meiryo, sans-serif;
}
```
and I can see this in the actual HTML file. However, this plugin's HTML preview can't be reflected.
Can I change the font used in JavaFX preview?

**Comment by vsch** [comment]
@hokuto-k, the preview CSS uses classes for the containers so it overrides the settings on the body element.

You should modify the font settings and use it as the CSS override for the preview:

```css
.markdown-body,
.wiki-body {
    font-family: Helvetica, Arial, "Helvetica Neue", "Segoe UI", freesans, sans-serif;
    font-size: 16px;
    line-height: 1.6;
}
```

**Comment by hokuto-k** [comment]
@vsch 
Thanks, I will try it.

**Comment by ddnexus** [comment]
I just tried that, but it looks like it works only for the regular text. The headlines don't change. What selector should I use to get also the h1, h2, h3, ... 
And actually all the text... I need to change the font-family in all the preview.

**Comment by vsch** [comment]
@ddnexus, the font settings in css for headings are defined as:

```css
h1,
h2,
h3,
h4,
h5,
h6 {
    font-family: Helvetica, "Helvetica Neue", Arial, freesans, sans-serif;
    line-height: 1.1;
    margin-bottom: 15px;
    margin-top: 15px;
}

```

I didn't notice it in there. I will remove it for next release to make headings use the markdown-body and wiki-body container fonts.
