### ISSUE TITLE
export to pdf error (when Chinese in content )

### ISSUE THREAD

**Issue by sholong** [vsch/idea-multimarkdown#533]
![tim 20171205183319](https://user-images.githubusercontent.com/7708380/33602635-e57e6330-d9ea-11e7-8890-2bf0d429b92d.png)
![tim 20171205183350](https://user-images.githubusercontent.com/7708380/33602637-e70b8638-d9ea-11e7-82fa-63f0c5fc8382.png)

**Comment by vsch** [comment]
@sholong, it is a limitation of the openhtmltopdf library which is used by the plugin.

The library needs additional fonts that have the necessary characters and html changes that will change the text to use those fonts.

This is covered by the issue for the library: https://github.com/danfickle/openhtmltopdf/issues/129

I am looking into how this can be handled by the plugin.

**Comment by vsch** [comment]
@sholong, fixed in next EAP for non-latin fonts by including [Noto](https://www.google.com/get/noto/) Serif/Sans/Mono fonts with the plugin allowing adding `noto-serif`, `noto-sans` and `noto-mono` families to CSS to allow PDF to use these for rendering text.

However, the PDF converter requires TrueType fonts and Noto CJK fonts are OpenFonts which cannot be used. The solution is to download a TrueType Unicode font that supports CJK character set and add it to the custom rendering profile to be used for PDF.

For my test I used `arialuni.ttf` from https://www.wfonts.com/font/arial-unicode-ms

By creating a custom rendering profile for PDF export with CSS Text (see [Rendering-Profiles-Settings](https://github.com/vsch/idea-multimarkdown/wiki/Rendering-Profiles-Settings)):

```css
@font-face {
  font-family: 'noto-cjk';
  src: url('file:///Users/vlad/src/fonts/arialuni.ttf');
  font-weight: normal;
  font-style: normal;	
}

.markdown-body,
.wiki-body {
    font-family: 'noto-sans', 'noto-cjk', Arial, "Helvetica Neue", "Segoe UI", freesans, sans-serif;
    font-size: 16px;
    line-height: 1.6;
}

var,
code,
kbd,
pre {
    font: 0.9em 'noto-mono', Consolas,Inconsolata,Courier,monospace;
}

```

And turning off all stylesheets and turning off HTML Generation option: `Add page header` for the custom profile.

Then setting Rendering Settings PDF profile to the above created rendering profile so PDF uses the custom CSS and HTML Generation.

The following markdown:

``````markdown
1. 0.40.68 test
   ------------

## Reply

Я ожидал увидеть в PDF текст и изображения такие же, как в превью
плагина, но что-то пошло не так

`Я ожидал`

```puml
A -> D 
```

|  字段名  | 说明                         | 是否必须 |  备注  |
|---------|:----------------------------|---------|--------|
| status  | 状态码                       | 是      | String |
| result  | 内容主体                     | 否      | Object |
| message | 异常情况的错误信息，供显示给用户 | 否      | String |
[  ]

异常情 况 的 错误 信息, mixed chars width wrapping mode test 供显 示给用户
异常情况的 错 误信息 供显 示给 用户 异常情 况的错误 信息，供显示给用户
异常情况的错 误信息，供显 示给用户 异常情况 的错误信息，供显示给用户 异常 情况的
错 误 信息，供显 示给 用户
``````

Renders in PDF as:

![screenshot_533pdf](https://user-images.githubusercontent.com/10299086/51696435-7ac80480-1fd3-11e9-8ea3-7caa273ff181.png)

Exports to PDF [533.pdf](https://github.com/vsch/idea-multimarkdown/files/2792834/533.pdf)

I will post here when the EAP is available for download.
