### ISSUE TITLE
Updated to expanded version and now JavaFX WebView won't render bold or italic

### ISSUE THREAD

**Issue by pmneve** [vsch/idea-multimarkdown#749]
Switching to swing corrects this but removes scrolling synch and table of contents generation.

What should I look in the settings to try to fix this?  And what do you need to see to help pin it down?

**Comment by vsch** [comment]
@pmneve, what OS are you on? Usually this occurs on Linux due to difference of installed fonts.

Preview bold requires a font family to have normal, bold, italic and bold-italic versions installed. Otherwise the variants will display as normal.

Issue #696 discusses this for non-latin fonts.

The default fonts used for preview are defined by:

```css
.markdown-body,
.wiki-body {
    font-family: Helvetica, Arial, "Helvetica Neue", "Segoe UI", freesans, sans-serif;
    overflow: hidden;
    word-wrap: break-word;
    font-size: 14px;
}
```

If you add the above into custom CSS text then you can edit the font-family list or re-order the fonts to have a font which has bold style font installed on your os:

![Screenshot_Stylesheet](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Stylesheet.png)
